# Generated by Django 2.2.4 on 2019-09-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imageupload',
            new_name='Imageuploaddraw',
        ),
    ]
