# Generated by Django 2.2.4 on 2019-09-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20190905_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='cover',
            new_name='img_url',
        ),
    ]
