# Generated by Django 2.2.4 on 2019-09-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20190905_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('date_of_search', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='img_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
