# Generated by Django 2.2.4 on 2019-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20190905_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='img_url',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
