# Generated by Django 2.2.4 on 2019-09-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20190905_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image_url',
        ),
    ]
