# Generated by Django 2.2.4 on 2019-09-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20190925_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='date_of_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
